# =========================================
# Stage 1: Develop the React.js Application
# =========================================

FROM dhi.io/bun:1.3.14-alpine3.22-dev AS dev

WORKDIR /app

COPY package.json bun.lock* bun.lockb* ./

# Install project dependencies
RUN --mount=type=cache,target=/root/.bun/install/cache \
  if [ -f bun.lock ] || [ -f bun.lockb ]; then \
  bun install --frozen-lockfile; \
  else \
  echo "No lockfile found." && exit 1; \
  fi

COPY . .

EXPOSE 5173

CMD ["bun", "run", "dev"]
