/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDeploymentRouteRouteImport } from './routes/_authenticated/deployment/route'
import { Route as AuthenticatedMlAuditingRouteRouteImport } from './routes/_authenticated/ml-auditing/route'
import { Route as AuthenticatedSystemHealthRouteRouteImport } from './routes/_authenticated/system-health/route'
import { Route as AuthenticatedUserManagementRouteRouteImport } from './routes/_authenticated/user-management/route'
import { Route as AuthenticatedDeploymentIndexRouteImport } from './routes/_authenticated/deployment/index'
import { Route as AuthenticatedMlAuditingIndexRouteImport } from './routes/_authenticated/ml-auditing/index'
import { Route as AuthenticatedSystemHealthIndexRouteImport } from './routes/_authenticated/system-health/index'
import { Route as AuthenticatedUserManagementIndexRouteImport } from './routes/_authenticated/user-management/index'
import { Route as UnauthenticatedAuthSignInRouteImport } from './routes/_unauthenticated/auth/sign-in'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeploymentRouteRoute =
  AuthenticatedDeploymentRouteRouteImport.update({
    id: '/deployment',
    path: '/deployment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMlAuditingRouteRoute =
  AuthenticatedMlAuditingRouteRouteImport.update({
    id: '/ml-auditing',
    path: '/ml-auditing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemHealthRouteRoute =
  AuthenticatedSystemHealthRouteRouteImport.update({
    id: '/system-health',
    path: '/system-health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserManagementRouteRoute =
  AuthenticatedUserManagementRouteRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeploymentIndexRoute =
  AuthenticatedDeploymentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDeploymentRouteRoute,
  } as any)
const AuthenticatedMlAuditingIndexRoute =
  AuthenticatedMlAuditingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMlAuditingRouteRoute,
  } as any)
const AuthenticatedSystemHealthIndexRoute =
  AuthenticatedSystemHealthIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSystemHealthRouteRoute,
  } as any)
const AuthenticatedUserManagementIndexRoute =
  AuthenticatedUserManagementIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUserManagementRouteRoute,
  } as any)
const UnauthenticatedAuthSignInRoute =
  UnauthenticatedAuthSignInRouteImport.update({
    id: '/_unauthenticated/auth/sign-in',
    path: '/auth/sign-in',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/deployment': typeof AuthenticatedDeploymentRouteRouteWithChildren
  '/ml-auditing': typeof AuthenticatedMlAuditingRouteRouteWithChildren
  '/system-health': typeof AuthenticatedSystemHealthRouteRouteWithChildren
  '/user-management': typeof AuthenticatedUserManagementRouteRouteWithChildren
  '/auth/sign-in': typeof UnauthenticatedAuthSignInRoute
  '/deployment/': typeof AuthenticatedDeploymentIndexRoute
  '/ml-auditing/': typeof AuthenticatedMlAuditingIndexRoute
  '/system-health/': typeof AuthenticatedSystemHealthIndexRoute
  '/user-management/': typeof AuthenticatedUserManagementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/auth/sign-in': typeof UnauthenticatedAuthSignInRoute
  '/deployment': typeof AuthenticatedDeploymentIndexRoute
  '/ml-auditing': typeof AuthenticatedMlAuditingIndexRoute
  '/system-health': typeof AuthenticatedSystemHealthIndexRoute
  '/user-management': typeof AuthenticatedUserManagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/deployment': typeof AuthenticatedDeploymentRouteRouteWithChildren
  '/_authenticated/ml-auditing': typeof AuthenticatedMlAuditingRouteRouteWithChildren
  '/_authenticated/system-health': typeof AuthenticatedSystemHealthRouteRouteWithChildren
  '/_authenticated/user-management': typeof AuthenticatedUserManagementRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_unauthenticated/auth/sign-in': typeof UnauthenticatedAuthSignInRoute
  '/_authenticated/deployment/': typeof AuthenticatedDeploymentIndexRoute
  '/_authenticated/ml-auditing/': typeof AuthenticatedMlAuditingIndexRoute
  '/_authenticated/system-health/': typeof AuthenticatedSystemHealthIndexRoute
  '/_authenticated/user-management/': typeof AuthenticatedUserManagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deployment'
    | '/ml-auditing'
    | '/system-health'
    | '/user-management'
    | '/auth/sign-in'
    | '/deployment/'
    | '/ml-auditing/'
    | '/system-health/'
    | '/user-management/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/deployment'
    | '/ml-auditing'
    | '/system-health'
    | '/user-management'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/deployment'
    | '/_authenticated/ml-auditing'
    | '/_authenticated/system-health'
    | '/_authenticated/user-management'
    | '/_authenticated/'
    | '/_unauthenticated/auth/sign-in'
    | '/_authenticated/deployment/'
    | '/_authenticated/ml-auditing/'
    | '/_authenticated/system-health/'
    | '/_authenticated/user-management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  UnauthenticatedAuthSignInRoute: typeof UnauthenticatedAuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deployment': {
      id: '/_authenticated/deployment'
      path: '/deployment'
      fullPath: '/deployment'
      preLoaderRoute: typeof AuthenticatedDeploymentRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ml-auditing': {
      id: '/_authenticated/ml-auditing'
      path: '/ml-auditing'
      fullPath: '/ml-auditing'
      preLoaderRoute: typeof AuthenticatedMlAuditingRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system-health': {
      id: '/_authenticated/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof AuthenticatedSystemHealthRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user-management': {
      id: '/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof AuthenticatedUserManagementRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deployment/': {
      id: '/_authenticated/deployment/'
      path: '/'
      fullPath: '/deployment/'
      preLoaderRoute: typeof AuthenticatedDeploymentIndexRouteImport
      parentRoute: typeof AuthenticatedDeploymentRouteRoute
    }
    '/_authenticated/ml-auditing/': {
      id: '/_authenticated/ml-auditing/'
      path: '/'
      fullPath: '/ml-auditing/'
      preLoaderRoute: typeof AuthenticatedMlAuditingIndexRouteImport
      parentRoute: typeof AuthenticatedMlAuditingRouteRoute
    }
    '/_authenticated/system-health/': {
      id: '/_authenticated/system-health/'
      path: '/'
      fullPath: '/system-health/'
      preLoaderRoute: typeof AuthenticatedSystemHealthIndexRouteImport
      parentRoute: typeof AuthenticatedSystemHealthRouteRoute
    }
    '/_authenticated/user-management/': {
      id: '/_authenticated/user-management/'
      path: '/'
      fullPath: '/user-management/'
      preLoaderRoute: typeof AuthenticatedUserManagementIndexRouteImport
      parentRoute: typeof AuthenticatedUserManagementRouteRoute
    }
    '/_unauthenticated/auth/sign-in': {
      id: '/_unauthenticated/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof UnauthenticatedAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDeploymentRouteRouteChildren {
  AuthenticatedDeploymentIndexRoute: typeof AuthenticatedDeploymentIndexRoute
}

const AuthenticatedDeploymentRouteRouteChildren: AuthenticatedDeploymentRouteRouteChildren =
  {
    AuthenticatedDeploymentIndexRoute: AuthenticatedDeploymentIndexRoute,
  }

const AuthenticatedDeploymentRouteRouteWithChildren =
  AuthenticatedDeploymentRouteRoute._addFileChildren(
    AuthenticatedDeploymentRouteRouteChildren,
  )

interface AuthenticatedMlAuditingRouteRouteChildren {
  AuthenticatedMlAuditingIndexRoute: typeof AuthenticatedMlAuditingIndexRoute
}

const AuthenticatedMlAuditingRouteRouteChildren: AuthenticatedMlAuditingRouteRouteChildren =
  {
    AuthenticatedMlAuditingIndexRoute: AuthenticatedMlAuditingIndexRoute,
  }

const AuthenticatedMlAuditingRouteRouteWithChildren =
  AuthenticatedMlAuditingRouteRoute._addFileChildren(
    AuthenticatedMlAuditingRouteRouteChildren,
  )

interface AuthenticatedSystemHealthRouteRouteChildren {
  AuthenticatedSystemHealthIndexRoute: typeof AuthenticatedSystemHealthIndexRoute
}

const AuthenticatedSystemHealthRouteRouteChildren: AuthenticatedSystemHealthRouteRouteChildren =
  {
    AuthenticatedSystemHealthIndexRoute: AuthenticatedSystemHealthIndexRoute,
  }

const AuthenticatedSystemHealthRouteRouteWithChildren =
  AuthenticatedSystemHealthRouteRoute._addFileChildren(
    AuthenticatedSystemHealthRouteRouteChildren,
  )

interface AuthenticatedUserManagementRouteRouteChildren {
  AuthenticatedUserManagementIndexRoute: typeof AuthenticatedUserManagementIndexRoute
}

const AuthenticatedUserManagementRouteRouteChildren: AuthenticatedUserManagementRouteRouteChildren =
  {
    AuthenticatedUserManagementIndexRoute:
      AuthenticatedUserManagementIndexRoute,
  }

const AuthenticatedUserManagementRouteRouteWithChildren =
  AuthenticatedUserManagementRouteRoute._addFileChildren(
    AuthenticatedUserManagementRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDeploymentRouteRoute: typeof AuthenticatedDeploymentRouteRouteWithChildren
  AuthenticatedMlAuditingRouteRoute: typeof AuthenticatedMlAuditingRouteRouteWithChildren
  AuthenticatedSystemHealthRouteRoute: typeof AuthenticatedSystemHealthRouteRouteWithChildren
  AuthenticatedUserManagementRouteRoute: typeof AuthenticatedUserManagementRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDeploymentRouteRoute:
    AuthenticatedDeploymentRouteRouteWithChildren,
  AuthenticatedMlAuditingRouteRoute:
    AuthenticatedMlAuditingRouteRouteWithChildren,
  AuthenticatedSystemHealthRouteRoute:
    AuthenticatedSystemHealthRouteRouteWithChildren,
  AuthenticatedUserManagementRouteRoute:
    AuthenticatedUserManagementRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  UnauthenticatedAuthSignInRoute: UnauthenticatedAuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
