/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardDeploymentRouteRouteImport } from './routes/_dashboard/deployment/route'
import { Route as DashboardMlAuditingRouteRouteImport } from './routes/_dashboard/ml-auditing/route'
import { Route as DashboardSystemHealthRouteRouteImport } from './routes/_dashboard/system-health/route'
import { Route as DashboardUserManagementRouteRouteImport } from './routes/_dashboard/user-management/route'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as DashboardDeploymentIndexRouteImport } from './routes/_dashboard/deployment/index'
import { Route as DashboardMlAuditingIndexRouteImport } from './routes/_dashboard/ml-auditing/index'
import { Route as DashboardSystemHealthIndexRouteImport } from './routes/_dashboard/system-health/index'
import { Route as DashboardUserManagementIndexRouteImport } from './routes/_dashboard/user-management/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDeploymentRouteRoute =
  DashboardDeploymentRouteRouteImport.update({
    id: '/deployment',
    path: '/deployment',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardMlAuditingRouteRoute =
  DashboardMlAuditingRouteRouteImport.update({
    id: '/ml-auditing',
    path: '/ml-auditing',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSystemHealthRouteRoute =
  DashboardSystemHealthRouteRouteImport.update({
    id: '/system-health',
    path: '/system-health',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardUserManagementRouteRoute =
  DashboardUserManagementRouteRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDeploymentIndexRoute =
  DashboardDeploymentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDeploymentRouteRoute,
  } as any)
const DashboardMlAuditingIndexRoute =
  DashboardMlAuditingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardMlAuditingRouteRoute,
  } as any)
const DashboardSystemHealthIndexRoute =
  DashboardSystemHealthIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardSystemHealthRouteRoute,
  } as any)
const DashboardUserManagementIndexRoute =
  DashboardUserManagementIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardUserManagementRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/deployment': typeof DashboardDeploymentRouteRouteWithChildren
  '/ml-auditing': typeof DashboardMlAuditingRouteRouteWithChildren
  '/system-health': typeof DashboardSystemHealthRouteRouteWithChildren
  '/user-management': typeof DashboardUserManagementRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/deployment/': typeof DashboardDeploymentIndexRoute
  '/ml-auditing/': typeof DashboardMlAuditingIndexRoute
  '/system-health/': typeof DashboardSystemHealthIndexRoute
  '/user-management/': typeof DashboardUserManagementIndexRoute
}
export interface FileRoutesByTo {
  '/auth/sign-in': typeof AuthSignInRoute
  '/': typeof DashboardIndexRoute
  '/deployment': typeof DashboardDeploymentIndexRoute
  '/ml-auditing': typeof DashboardMlAuditingIndexRoute
  '/system-health': typeof DashboardSystemHealthIndexRoute
  '/user-management': typeof DashboardUserManagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_dashboard/deployment': typeof DashboardDeploymentRouteRouteWithChildren
  '/_dashboard/ml-auditing': typeof DashboardMlAuditingRouteRouteWithChildren
  '/_dashboard/system-health': typeof DashboardSystemHealthRouteRouteWithChildren
  '/_dashboard/user-management': typeof DashboardUserManagementRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/deployment/': typeof DashboardDeploymentIndexRoute
  '/_dashboard/ml-auditing/': typeof DashboardMlAuditingIndexRoute
  '/_dashboard/system-health/': typeof DashboardSystemHealthIndexRoute
  '/_dashboard/user-management/': typeof DashboardUserManagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deployment'
    | '/ml-auditing'
    | '/system-health'
    | '/user-management'
    | '/auth/sign-in'
    | '/deployment/'
    | '/ml-auditing/'
    | '/system-health/'
    | '/user-management/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/sign-in'
    | '/'
    | '/deployment'
    | '/ml-auditing'
    | '/system-health'
    | '/user-management'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/deployment'
    | '/_dashboard/ml-auditing'
    | '/_dashboard/system-health'
    | '/_dashboard/user-management'
    | '/auth/sign-in'
    | '/_dashboard/'
    | '/_dashboard/deployment/'
    | '/_dashboard/ml-auditing/'
    | '/_dashboard/system-health/'
    | '/_dashboard/user-management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/deployment': {
      id: '/_dashboard/deployment'
      path: '/deployment'
      fullPath: '/deployment'
      preLoaderRoute: typeof DashboardDeploymentRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/ml-auditing': {
      id: '/_dashboard/ml-auditing'
      path: '/ml-auditing'
      fullPath: '/ml-auditing'
      preLoaderRoute: typeof DashboardMlAuditingRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/system-health': {
      id: '/_dashboard/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof DashboardSystemHealthRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/user-management': {
      id: '/_dashboard/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof DashboardUserManagementRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/deployment/': {
      id: '/_dashboard/deployment/'
      path: '/'
      fullPath: '/deployment/'
      preLoaderRoute: typeof DashboardDeploymentIndexRouteImport
      parentRoute: typeof DashboardDeploymentRouteRoute
    }
    '/_dashboard/ml-auditing/': {
      id: '/_dashboard/ml-auditing/'
      path: '/'
      fullPath: '/ml-auditing/'
      preLoaderRoute: typeof DashboardMlAuditingIndexRouteImport
      parentRoute: typeof DashboardMlAuditingRouteRoute
    }
    '/_dashboard/system-health/': {
      id: '/_dashboard/system-health/'
      path: '/'
      fullPath: '/system-health/'
      preLoaderRoute: typeof DashboardSystemHealthIndexRouteImport
      parentRoute: typeof DashboardSystemHealthRouteRoute
    }
    '/_dashboard/user-management/': {
      id: '/_dashboard/user-management/'
      path: '/'
      fullPath: '/user-management/'
      preLoaderRoute: typeof DashboardUserManagementIndexRouteImport
      parentRoute: typeof DashboardUserManagementRouteRoute
    }
  }
}

interface DashboardDeploymentRouteRouteChildren {
  DashboardDeploymentIndexRoute: typeof DashboardDeploymentIndexRoute
}

const DashboardDeploymentRouteRouteChildren: DashboardDeploymentRouteRouteChildren =
  {
    DashboardDeploymentIndexRoute: DashboardDeploymentIndexRoute,
  }

const DashboardDeploymentRouteRouteWithChildren =
  DashboardDeploymentRouteRoute._addFileChildren(
    DashboardDeploymentRouteRouteChildren,
  )

interface DashboardMlAuditingRouteRouteChildren {
  DashboardMlAuditingIndexRoute: typeof DashboardMlAuditingIndexRoute
}

const DashboardMlAuditingRouteRouteChildren: DashboardMlAuditingRouteRouteChildren =
  {
    DashboardMlAuditingIndexRoute: DashboardMlAuditingIndexRoute,
  }

const DashboardMlAuditingRouteRouteWithChildren =
  DashboardMlAuditingRouteRoute._addFileChildren(
    DashboardMlAuditingRouteRouteChildren,
  )

interface DashboardSystemHealthRouteRouteChildren {
  DashboardSystemHealthIndexRoute: typeof DashboardSystemHealthIndexRoute
}

const DashboardSystemHealthRouteRouteChildren: DashboardSystemHealthRouteRouteChildren =
  {
    DashboardSystemHealthIndexRoute: DashboardSystemHealthIndexRoute,
  }

const DashboardSystemHealthRouteRouteWithChildren =
  DashboardSystemHealthRouteRoute._addFileChildren(
    DashboardSystemHealthRouteRouteChildren,
  )

interface DashboardUserManagementRouteRouteChildren {
  DashboardUserManagementIndexRoute: typeof DashboardUserManagementIndexRoute
}

const DashboardUserManagementRouteRouteChildren: DashboardUserManagementRouteRouteChildren =
  {
    DashboardUserManagementIndexRoute: DashboardUserManagementIndexRoute,
  }

const DashboardUserManagementRouteRouteWithChildren =
  DashboardUserManagementRouteRoute._addFileChildren(
    DashboardUserManagementRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardDeploymentRouteRoute: typeof DashboardDeploymentRouteRouteWithChildren
  DashboardMlAuditingRouteRoute: typeof DashboardMlAuditingRouteRouteWithChildren
  DashboardSystemHealthRouteRoute: typeof DashboardSystemHealthRouteRouteWithChildren
  DashboardUserManagementRouteRoute: typeof DashboardUserManagementRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDeploymentRouteRoute: DashboardDeploymentRouteRouteWithChildren,
  DashboardMlAuditingRouteRoute: DashboardMlAuditingRouteRouteWithChildren,
  DashboardSystemHealthRouteRoute: DashboardSystemHealthRouteRouteWithChildren,
  DashboardUserManagementRouteRoute:
    DashboardUserManagementRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
